name: 'dbt_training'
version: '1.0'
config-version: 2

profile: 'dbt_training'

# Paths
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]

# Build output
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_training:
    raw:
      +materialized: view
      +database: raw_analytics
      +schema: raw
    stg:
      +materialized: table
      +database: stg_analytics
      +schema: stg

seeds:
  dbt_training:
    +database: raw_analytics
    +schema: seed_data

    customers:
      +column_types:
        id: integer
        first_name: string
        last_name: string

    orders:
      +column_types:
        id: integer
        user_id: integer
        order_date: date
        status: string

    payments:
      +column_types:
        id: integer
        order_id: integer
        payment_method: string
        amount: number
