name: 'dbt_training'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dbt_training:
    staging:
      +materialized: view
    marts:
      +materialized: table